version: "3.9"

services:
  web:
    build: ./web
    container_name: desafio3_web
    ports:
      - "8081:8080"
    environment:
      - DATABASE_HOST=db
      - CACHE_HOST=cache
    depends_on:
      - db
      - cache
    networks:
      - desafio3_net

  db:
    image: postgres:16-alpine
    container_name: desafio3_db
    environment:
      POSTGRES_DB: desafio3
      POSTGRES_USER: desafio3
      POSTGRES_PASSWORD: desafio3
    networks:
      - desafio3_net

  cache:
    image: redis:7-alpine
    container_name: desafio3_cache
    networks:
      - desafio3_net

networks:
  desafio3_net:
    driver: bridge
